name: period_tracking
description: "A period tracking project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_spinkit: ^5.2.1
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^6.1.0
  fluttertoast: ^8.2.8
  timeago: ^3.3.0
  shimmer: ^3.0.0
  photo_view: ^0.15.0
  webview_flutter: ^4.10.0
  dotted_border: ^2.1.0
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  flutter_typeahead: ^5.2.0
  geocoding: ^3.0.0
  video_player: ^2.9.2
  country_picker: ^2.0.27
  intl_phone_field: ^3.2.0
  flutter_html:
  tcard: ^1.3.5
  carousel_slider: ^5.0.0

  logger: ^2.5.0
  app_settings: ^5.1.1
  map_picker: ^0.0.3
  google_fonts: ^6.2.1
  get_storage: ^2.1.1
  jwt_decoder: ^2.0.1
  lottie: ^3.1.3

  shared_preferences:
  flutter_screenutil:
  flutter_svg:
  animated_notch_bottom_bar:
  flutter_staggered_grid_view:
  intl:
  image_picker:
  cached_network_image:
  circle_nav_bar:
  grouped_list:
  flutter_chat_bubble:
  socket_io_client:
  file_picker:
  http:
  mime_type:
  image:
  http_parser:
  path_provider:
  mime: ^2.0.0
  pin_code_fields: ^8.0.1
  url_launcher: ^6.3.1
  anim_search_bar:
  table_calendar:
  fl_chart: ^0.65.0
  sqflite:
  path:
  syncfusion_flutter_sliders:
  flutter_pdfview:
  flutter_phoenix: ^1.1.1





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/

